site_name: ComputerScience
pages:
- "Home": 'index.md'
- "Database":
  - "Introduction": "database.md"
  - "SQL": "db_sql.md"
  - "MySQL": "db_mysql.md"
  - "Redis": "db_redis.md"
- "Networking": 'networking.md'
- "OS":
  - "Introduction": 'os.md'
  - "Linux": 'os_linux.md'
  - "CentOS": 'os_centos.md'
  - "Ubuntu": 'os_ubuntu.md'
  - "Windows": 'os_windows.md'
- "UX/UI": 'ux.md'
- "SA": 'software_architecture.md'
- "Licenses": "licenses.md"
markdown_extensions:
    - footnotes
